version: '3.8'
services:
  sar-trivia-game:
    container_name: sar-trivia-game
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - '${PORT}:80'
      - '3000:3000'
    env_file:
      - .env
    networks:
      - 500Historias
networks:
  500Historias:
    driver: bridge
